# Generated by Django 5.2.7 on 2025-10-08 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='должность')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='организация')),
                ('access_level', models.IntegerField(choices=[(0, 'Гость'), (1, 'Сотрудник'), (2, 'Менеджер'), (3, 'Администратор')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
