# Generated by Django 5.2.6 on 2025-09-15 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('BLACK', 'BLACK')], default='WHITE', max_length=5),
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='projectapp.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'active'], name='projectapp__device__c5e7b6_idx')],
            },
        ),
    ]
