# Generated by Django 5.2 on 2025-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_remove_device_created_at_remove_device_uid_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devicetoken',
            name='projectapp__device__c5e7b6_idx',
        ),
        migrations.RenameField(
            model_name='devicetoken',
            old_name='valid_from',
            new_name='expires_at',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='active',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='token_hash',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(default='default', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default='default_device', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
