# Generated by Django 5.2.6 on 2025-10-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_remove_devicetoken_projectapp__device__c5e7b6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
